#!/usr/bin/env bash

cp Cargo.toml Cargo.toml.bak
sed -i '' 's/"main\.rs"/"main_osx.rs"/' Cargo.toml

# Run cargo build. It will fail. Cut out the attempted rustc command. Append our args and run again.
rustc_cmd="$(cargo build -v 2>/dev/null | tee /dev/tty | grep main_osx | cut -d\` -f2)"
$rustc_cmd -C link-args="-lSDLmain -lSDL -Wl,-framework,Cocoa"

mv Cargo.toml.bak Cargo.toml

